/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as RegistryRouteImport } from './routes/registry'
import { Route as ProtectRouteImport } from './routes/protect'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistryRoute = RegistryRouteImport.update({
  id: '/registry',
  path: '/registry',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectRoute = ProtectRouteImport.update({
  id: '/protect',
  path: '/protect',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/products': typeof ProductsRoute
  '/protect': typeof ProtectRoute
  '/registry': typeof RegistryRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/products': typeof ProductsRoute
  '/protect': typeof ProtectRoute
  '/registry': typeof RegistryRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/docs': typeof DocsRoute
  '/how-it-works': typeof HowItWorksRoute
  '/markets': typeof MarketsRoute
  '/products': typeof ProductsRoute
  '/protect': typeof ProtectRoute
  '/registry': typeof RegistryRoute
  '/transparency': typeof TransparencyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/how-it-works'
    | '/markets'
    | '/products'
    | '/protect'
    | '/registry'
    | '/transparency'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/how-it-works'
    | '/markets'
    | '/products'
    | '/protect'
    | '/registry'
    | '/transparency'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/docs'
    | '/how-it-works'
    | '/markets'
    | '/products'
    | '/protect'
    | '/registry'
    | '/transparency'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DocsRoute: typeof DocsRoute
  HowItWorksRoute: typeof HowItWorksRoute
  MarketsRoute: typeof MarketsRoute
  ProductsRoute: typeof ProductsRoute
  ProtectRoute: typeof ProtectRoute
  RegistryRoute: typeof RegistryRoute
  TransparencyRoute: typeof TransparencyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registry': {
      id: '/registry'
      path: '/registry'
      fullPath: '/registry'
      preLoaderRoute: typeof RegistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protect': {
      id: '/protect'
      path: '/protect'
      fullPath: '/protect'
      preLoaderRoute: typeof ProtectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DocsRoute: DocsRoute,
  HowItWorksRoute: HowItWorksRoute,
  MarketsRoute: MarketsRoute,
  ProductsRoute: ProductsRoute,
  ProtectRoute: ProtectRoute,
  RegistryRoute: RegistryRoute,
  TransparencyRoute: TransparencyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
